//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/VisualStudioProjects/VSCode/pjpProject/Language.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class LanguageParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, PROCEDURE=21, INT=22, FLOAT=23, BOOL=24, 
		STRING=25, READ=26, WRITE=27, IF=28, ELSE=29, WHILE=30, BOOL_LIT=31, FLOAT_LIT=32, 
		INT_LIT=33, STR_LIT=34, ID=35, LINE_COMMENT=36, WS=37;
	public const int
		RULE_program = 0, RULE_topLevel = 1, RULE_procDecl = 2, RULE_statement = 3, 
		RULE_type = 4, RULE_expr = 5;
	public static readonly string[] ruleNames = {
		"program", "topLevel", "procDecl", "statement", "type", "expr"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'{'", "'}'", "';'", "','", "'-'", "'!'", "'*'", "'/'", 
		"'%'", "'+'", "'.'", "'<'", "'>'", "'=='", "'!='", "'&&'", "'||'", "'='", 
		"'procedure'", "'int'", "'float'", "'bool'", "'string'", "'read'", "'write'", 
		"'if'", "'else'", "'while'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "PROCEDURE", "INT", 
		"FLOAT", "BOOL", "STRING", "READ", "WRITE", "IF", "ELSE", "WHILE", "BOOL_LIT", 
		"FLOAT_LIT", "INT_LIT", "STR_LIT", "ID", "LINE_COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Language.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static LanguageParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public LanguageParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public LanguageParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(LanguageParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TopLevelContext[] topLevel() {
			return GetRuleContexts<TopLevelContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TopLevelContext topLevel(int i) {
			return GetRuleContext<TopLevelContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 15;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 68180509098L) != 0)) {
				{
				{
				State = 12;
				topLevel();
				}
				}
				State = 17;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 18;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TopLevelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ProcDeclContext procDecl() {
			return GetRuleContext<ProcDeclContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public TopLevelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_topLevel; } }
	}

	[RuleVersion(0)]
	public TopLevelContext topLevel() {
		TopLevelContext _localctx = new TopLevelContext(Context, State);
		EnterRule(_localctx, 2, RULE_topLevel);
		try {
			State = 22;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case PROCEDURE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 20;
				procDecl();
				}
				break;
			case T__0:
			case T__2:
			case T__4:
			case T__6:
			case T__7:
			case INT:
			case FLOAT:
			case BOOL:
			case STRING:
			case READ:
			case WRITE:
			case IF:
			case WHILE:
			case BOOL_LIT:
			case FLOAT_LIT:
			case INT_LIT:
			case STR_LIT:
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 21;
				statement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ProcDeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PROCEDURE() { return GetToken(LanguageParser.PROCEDURE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LanguageParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ProcDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_procDecl; } }
	}

	[RuleVersion(0)]
	public ProcDeclContext procDecl() {
		ProcDeclContext _localctx = new ProcDeclContext(Context, State);
		EnterRule(_localctx, 4, RULE_procDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 24;
			Match(PROCEDURE);
			State = 25;
			Match(ID);
			State = 26;
			Match(T__0);
			State = 27;
			Match(T__1);
			State = 28;
			Match(T__2);
			State = 32;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 68178411946L) != 0)) {
				{
				{
				State = 29;
				statement();
				}
				}
				State = 34;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 35;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	 
		public StatementContext() { }
		public virtual void CopyFrom(StatementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ExprStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ExprStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class WhileStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(LanguageParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public WhileStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class CallStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LanguageParser.ID, 0); }
		public CallStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class ReadStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode READ() { return GetToken(LanguageParser.READ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(LanguageParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(LanguageParser.ID, i);
		}
		public ReadStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class IfStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(LanguageParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(LanguageParser.ELSE, 0); }
		public IfStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class BlockStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class DeclStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(LanguageParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(LanguageParser.ID, i);
		}
		public DeclStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class EmptyStmtContext : StatementContext {
		public EmptyStmtContext(StatementContext context) { CopyFrom(context); }
	}
	public partial class WriteStmtContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WRITE() { return GetToken(LanguageParser.WRITE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public WriteStmtContext(StatementContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 6, RULE_statement);
		int _la;
		try {
			State = 100;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				_localctx = new EmptyStmtContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 37;
				Match(T__4);
				}
				break;
			case 2:
				_localctx = new DeclStmtContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 38;
				type();
				State = 39;
				Match(ID);
				State = 44;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 40;
					Match(T__5);
					State = 41;
					Match(ID);
					}
					}
					State = 46;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 47;
				Match(T__4);
				}
				break;
			case 3:
				_localctx = new ExprStmtContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 49;
				expr(0);
				State = 50;
				Match(T__4);
				}
				break;
			case 4:
				_localctx = new ReadStmtContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 52;
				Match(READ);
				State = 53;
				Match(ID);
				State = 58;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 54;
					Match(T__5);
					State = 55;
					Match(ID);
					}
					}
					State = 60;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 61;
				Match(T__4);
				}
				break;
			case 5:
				_localctx = new WriteStmtContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 62;
				Match(WRITE);
				State = 63;
				expr(0);
				State = 68;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 64;
					Match(T__5);
					State = 65;
					expr(0);
					}
					}
					State = 70;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 71;
				Match(T__4);
				}
				break;
			case 6:
				_localctx = new BlockStmtContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 73;
				Match(T__2);
				State = 77;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 68178411946L) != 0)) {
					{
					{
					State = 74;
					statement();
					}
					}
					State = 79;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 80;
				Match(T__3);
				}
				break;
			case 7:
				_localctx = new IfStmtContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 81;
				Match(IF);
				State = 82;
				Match(T__0);
				State = 83;
				expr(0);
				State = 84;
				Match(T__1);
				State = 85;
				statement();
				State = 88;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
				case 1:
					{
					State = 86;
					Match(ELSE);
					State = 87;
					statement();
					}
					break;
				}
				}
				break;
			case 8:
				_localctx = new WhileStmtContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 90;
				Match(WHILE);
				State = 91;
				Match(T__0);
				State = 92;
				expr(0);
				State = 93;
				Match(T__1);
				State = 94;
				statement();
				}
				break;
			case 9:
				_localctx = new CallStmtContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 96;
				Match(ID);
				State = 97;
				Match(T__0);
				State = 98;
				Match(T__1);
				State = 99;
				Match(T__4);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(LanguageParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT() { return GetToken(LanguageParser.FLOAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOL() { return GetToken(LanguageParser.BOOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(LanguageParser.STRING, 0); }
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 8, RULE_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 62914560L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class OrExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public OrExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class ParenExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ParenExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class StrLitContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STR_LIT() { return GetToken(LanguageParser.STR_LIT, 0); }
		public StrLitContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class EqExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public EqExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class NotExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NotExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class UnaryMinusExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public UnaryMinusExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class FloatLitContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_LIT() { return GetToken(LanguageParser.FLOAT_LIT, 0); }
		public FloatLitContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class AddExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public AddExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class BoolLitContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOL_LIT() { return GetToken(LanguageParser.BOOL_LIT, 0); }
		public BoolLitContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class IntLitContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_LIT() { return GetToken(LanguageParser.INT_LIT, 0); }
		public IntLitContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class MulExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public MulExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class RelExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public RelExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class AssignExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public AssignExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class IdExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LanguageParser.ID, 0); }
		public IdExprContext(ExprContext context) { CopyFrom(context); }
	}
	public partial class AndExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public AndExprContext(ExprContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 10;
		EnterRecursionRule(_localctx, 10, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 118;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__6:
				{
				_localctx = new UnaryMinusExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 105;
				Match(T__6);
				State = 106;
				expr(15);
				}
				break;
			case T__7:
				{
				_localctx = new NotExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 107;
				Match(T__7);
				State = 108;
				expr(14);
				}
				break;
			case T__0:
				{
				_localctx = new ParenExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 109;
				Match(T__0);
				State = 110;
				expr(0);
				State = 111;
				Match(T__1);
				}
				break;
			case INT_LIT:
				{
				_localctx = new IntLitContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 113;
				Match(INT_LIT);
				}
				break;
			case FLOAT_LIT:
				{
				_localctx = new FloatLitContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 114;
				Match(FLOAT_LIT);
				}
				break;
			case BOOL_LIT:
				{
				_localctx = new BoolLitContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 115;
				Match(BOOL_LIT);
				}
				break;
			case STR_LIT:
				{
				_localctx = new StrLitContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 116;
				Match(STR_LIT);
				}
				break;
			case ID:
				{
				_localctx = new IdExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 117;
				Match(ID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 143;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 141;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
					case 1:
						{
						_localctx = new MulExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 120;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 121;
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 3584L) != 0)) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 122;
						expr(14);
						}
						break;
					case 2:
						{
						_localctx = new AddExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 123;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 124;
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 12416L) != 0)) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 125;
						expr(13);
						}
						break;
					case 3:
						{
						_localctx = new RelExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 126;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 127;
						_la = TokenStream.LA(1);
						if ( !(_la==T__13 || _la==T__14) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 128;
						expr(12);
						}
						break;
					case 4:
						{
						_localctx = new EqExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 129;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 130;
						_la = TokenStream.LA(1);
						if ( !(_la==T__15 || _la==T__16) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 131;
						expr(11);
						}
						break;
					case 5:
						{
						_localctx = new AndExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 132;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 133;
						Match(T__17);
						State = 134;
						expr(10);
						}
						break;
					case 6:
						{
						_localctx = new OrExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 135;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 136;
						Match(T__18);
						State = 137;
						expr(9);
						}
						break;
					case 7:
						{
						_localctx = new AssignExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 138;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 139;
						Match(T__19);
						State = 140;
						expr(7);
						}
						break;
					}
					} 
				}
				State = 145;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 5: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 13);
		case 1: return Precpred(Context, 12);
		case 2: return Precpred(Context, 11);
		case 3: return Precpred(Context, 10);
		case 4: return Precpred(Context, 9);
		case 5: return Precpred(Context, 8);
		case 6: return Precpred(Context, 7);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,37,147,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,1,0,5,0,14,
		8,0,10,0,12,0,17,9,0,1,0,1,0,1,1,1,1,3,1,23,8,1,1,2,1,2,1,2,1,2,1,2,1,
		2,5,2,31,8,2,10,2,12,2,34,9,2,1,2,1,2,1,3,1,3,1,3,1,3,1,3,5,3,43,8,3,10,
		3,12,3,46,9,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,5,3,57,8,3,10,3,12,3,
		60,9,3,1,3,1,3,1,3,1,3,1,3,5,3,67,8,3,10,3,12,3,70,9,3,1,3,1,3,1,3,1,3,
		5,3,76,8,3,10,3,12,3,79,9,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,3,3,89,8,3,
		1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,3,3,101,8,3,1,4,1,4,1,5,1,5,1,
		5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,3,5,119,8,5,1,5,1,5,1,5,
		1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,
		5,5,5,142,8,5,10,5,12,5,145,9,5,1,5,0,1,10,6,0,2,4,6,8,10,0,5,1,0,22,25,
		1,0,9,11,2,0,7,7,12,13,1,0,14,15,1,0,16,17,170,0,15,1,0,0,0,2,22,1,0,0,
		0,4,24,1,0,0,0,6,100,1,0,0,0,8,102,1,0,0,0,10,118,1,0,0,0,12,14,3,2,1,
		0,13,12,1,0,0,0,14,17,1,0,0,0,15,13,1,0,0,0,15,16,1,0,0,0,16,18,1,0,0,
		0,17,15,1,0,0,0,18,19,5,0,0,1,19,1,1,0,0,0,20,23,3,4,2,0,21,23,3,6,3,0,
		22,20,1,0,0,0,22,21,1,0,0,0,23,3,1,0,0,0,24,25,5,21,0,0,25,26,5,35,0,0,
		26,27,5,1,0,0,27,28,5,2,0,0,28,32,5,3,0,0,29,31,3,6,3,0,30,29,1,0,0,0,
		31,34,1,0,0,0,32,30,1,0,0,0,32,33,1,0,0,0,33,35,1,0,0,0,34,32,1,0,0,0,
		35,36,5,4,0,0,36,5,1,0,0,0,37,101,5,5,0,0,38,39,3,8,4,0,39,44,5,35,0,0,
		40,41,5,6,0,0,41,43,5,35,0,0,42,40,1,0,0,0,43,46,1,0,0,0,44,42,1,0,0,0,
		44,45,1,0,0,0,45,47,1,0,0,0,46,44,1,0,0,0,47,48,5,5,0,0,48,101,1,0,0,0,
		49,50,3,10,5,0,50,51,5,5,0,0,51,101,1,0,0,0,52,53,5,26,0,0,53,58,5,35,
		0,0,54,55,5,6,0,0,55,57,5,35,0,0,56,54,1,0,0,0,57,60,1,0,0,0,58,56,1,0,
		0,0,58,59,1,0,0,0,59,61,1,0,0,0,60,58,1,0,0,0,61,101,5,5,0,0,62,63,5,27,
		0,0,63,68,3,10,5,0,64,65,5,6,0,0,65,67,3,10,5,0,66,64,1,0,0,0,67,70,1,
		0,0,0,68,66,1,0,0,0,68,69,1,0,0,0,69,71,1,0,0,0,70,68,1,0,0,0,71,72,5,
		5,0,0,72,101,1,0,0,0,73,77,5,3,0,0,74,76,3,6,3,0,75,74,1,0,0,0,76,79,1,
		0,0,0,77,75,1,0,0,0,77,78,1,0,0,0,78,80,1,0,0,0,79,77,1,0,0,0,80,101,5,
		4,0,0,81,82,5,28,0,0,82,83,5,1,0,0,83,84,3,10,5,0,84,85,5,2,0,0,85,88,
		3,6,3,0,86,87,5,29,0,0,87,89,3,6,3,0,88,86,1,0,0,0,88,89,1,0,0,0,89,101,
		1,0,0,0,90,91,5,30,0,0,91,92,5,1,0,0,92,93,3,10,5,0,93,94,5,2,0,0,94,95,
		3,6,3,0,95,101,1,0,0,0,96,97,5,35,0,0,97,98,5,1,0,0,98,99,5,2,0,0,99,101,
		5,5,0,0,100,37,1,0,0,0,100,38,1,0,0,0,100,49,1,0,0,0,100,52,1,0,0,0,100,
		62,1,0,0,0,100,73,1,0,0,0,100,81,1,0,0,0,100,90,1,0,0,0,100,96,1,0,0,0,
		101,7,1,0,0,0,102,103,7,0,0,0,103,9,1,0,0,0,104,105,6,5,-1,0,105,106,5,
		7,0,0,106,119,3,10,5,15,107,108,5,8,0,0,108,119,3,10,5,14,109,110,5,1,
		0,0,110,111,3,10,5,0,111,112,5,2,0,0,112,119,1,0,0,0,113,119,5,33,0,0,
		114,119,5,32,0,0,115,119,5,31,0,0,116,119,5,34,0,0,117,119,5,35,0,0,118,
		104,1,0,0,0,118,107,1,0,0,0,118,109,1,0,0,0,118,113,1,0,0,0,118,114,1,
		0,0,0,118,115,1,0,0,0,118,116,1,0,0,0,118,117,1,0,0,0,119,143,1,0,0,0,
		120,121,10,13,0,0,121,122,7,1,0,0,122,142,3,10,5,14,123,124,10,12,0,0,
		124,125,7,2,0,0,125,142,3,10,5,13,126,127,10,11,0,0,127,128,7,3,0,0,128,
		142,3,10,5,12,129,130,10,10,0,0,130,131,7,4,0,0,131,142,3,10,5,11,132,
		133,10,9,0,0,133,134,5,18,0,0,134,142,3,10,5,10,135,136,10,8,0,0,136,137,
		5,19,0,0,137,142,3,10,5,9,138,139,10,7,0,0,139,140,5,20,0,0,140,142,3,
		10,5,7,141,120,1,0,0,0,141,123,1,0,0,0,141,126,1,0,0,0,141,129,1,0,0,0,
		141,132,1,0,0,0,141,135,1,0,0,0,141,138,1,0,0,0,142,145,1,0,0,0,143,141,
		1,0,0,0,143,144,1,0,0,0,144,11,1,0,0,0,145,143,1,0,0,0,12,15,22,32,44,
		58,68,77,88,100,118,141,143
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
